name: Test auf Self-Hosted Runner

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Python-Version anzeigen
        run: python --version

      - name: Beispielskript ausführen
        run: echo "Hallo von deinem eigenen Runner!"
