[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "omerssolar"
version = "1.0.1"
authors = [{ name = "Du" }]
description = "Omers Solar Dingel Dangel"
requires-python = ">=3.9"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]
